# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  build:  
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Running build
          command: yarn
          command: CI=true yarn build
  test:  
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Running test
          command: yarn
          command: yarn test
  hello:  
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Hello World!

workflows:
  sample: 
    jobs:
      - build
      - hello
      - test:
          requires:
            - hello

