const CartActionType = {
  TOGGLE_HIDDEN_CART: 'TOGGLE_HIDDEN_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartActionType;
